name: Lets give this a shot
on:
  issues:
    types: opened
- uses: stefanbuck/github-issue-parser@v2
  id: issue-parser
  with:
    template-path: .github/ISSUE_TEMPLATE/bug-report.yml

- run: echo '${{ steps.issue-parser.outputs.jsonString }}' > bug-details.json